ReferableUtils
eclipse-basyx/basyx-aas-web-ui pull request #175
Opened 2024-12-22 06:11 UTC by seicke

- Moved checkSemanticId from IDUtils (cause methods scope is referables)
- Add tests for all ReferableUtils methods
- Fixes of ReferableUtils methods regarding tests

2024-12-22 09:34 UTC, aaronzi requested changes

2024-12-22 09:34 UTC, aaronzi commented on aas-web-ui/src/utils/ReferableUtils.ts
For possible future support of multiple languages, could you please add a parameter to specify the language? The parameter should have a default set to 'en'

2024-12-22 09:34 UTC, aaronzi commented on aas-web-ui/tests/utils/Referable.test.ts
> +        const referable = checkSemanticIdTestDataset.referable; //e.g. the ID of a ConceptDescription
```suggestion
        const referable = checkSemanticIdTestDataset.referable; // e.g. the ID of a ConceptDescription
```

2024-12-22 09:37 UTC, aaronzi commented
Thank you for the PR :)

> * Moved checkSemanticId from IDUtils (cause methods scope is preferable)

you mean checkIdShort, right?
Please correct the names of all the variables where this naming mistake was made.

2024-12-23 05:59 UTC, seicke commented
Sorry for mixing-up the method names!
Yes, I mean checkIdShort.

2024-12-23 08:26 UTC, merged