Updates visualization compontents to the composition API
eclipse-basyx/basyx-aas-web-ui pull request #176
Opened 2024-12-22 08:43 UTC by seicke

2024-12-23 06:28 UTC, seicke commented
@aaronzi Before I continue with my work on the further visualizations, may I ask you to pre-review the nameplate visualization? Thanks in advance!

2024-12-23 13:34 UTC, aaronzi requested changes
THank you for the PR. I added some remarks as comments to the respective lines in the code.

2024-12-23 13:34 UTC, aaronzi commented on aas-web-ui/src/components/Plugins/Submodels/ContactInformation.vue
> +                                                {{ description.text }}
Please revert this cosmetic change. This seems to be caused by a local formatting setting

2024-12-23 13:34 UTC, aaronzi commented on aas-web-ui/src/components/Plugins/Submodels/ContactInformation.vue
> +                        </v-btn>
Please also remove this cosmetic change

2024-12-23 13:34 UTC, aaronzi commented on aas-web-ui/src/components/ComponentVisualization.vue
> +                        </component>
Please revert this cosmetic change.

2024-12-23 13:34 UTC, aaronzi commented on aas-web-ui/src/components/Plugins/Submodels/HandoverDocumentation.vue
> +                                                    {{ description.text }}
Please revert this cosmetic change.

2024-12-23 13:34 UTC, aaronzi commented on aas-web-ui/src/components/Plugins/Submodels/TechnicalData.vue
> +                                                {{ description.text }}
Please revert this cosmetic change.

2024-12-23 13:34 UTC, aaronzi commented on aas-web-ui/src/components/Plugins/Submodels/TechnicalData.vue
> +                                                {{ description.text }}
Please revert this cosmetic change.

2024-12-23 13:34 UTC, aaronzi commented on aas-web-ui/src/components/Plugins/Submodels/TimeSeriesData.vue
> +                        </v-btn>
Please revert this cosmetic change.

2024-12-23 13:34 UTC, aaronzi commented on aas-web-ui/src/components/Plugins/Submodels/TimeSeriesData.vue
> +                        </v-btn>
Please revert this cosmetic change.

2024-12-23 13:34 UTC, aaronzi commented on aas-web-ui/src/components/Plugins/Submodels/TimeSeriesData.vue
> +                        </v-btn>
Please revert this cosmetic change.

2024-12-23 13:34 UTC, aaronzi commented on aas-web-ui/src/components/Plugins/Submodels/TimeSeriesData.vue
> +                        </v-btn>
Please revert this cosmetic change.

2024-12-23 13:34 UTC, aaronzi commented on aas-web-ui/tsconfig.tsbuildinfo
Can you remove the changes to this file please

2024-12-23 13:34 UTC, aaronzi commented on aas-web-ui/src/components/Plugins/Submodels/Nameplate_v2.0.vue
> +    // import { useRequestHandling } from '@/composables/RequestHandling';
Please remove unused imports

2024-12-23 13:34 UTC, aaronzi commented on aas-web-ui/src/components/Plugins/Submodels/Nameplate_v2.0.vue
> +    // const { getAttachment } = useSMRepositoryClient();
Please remove unused composables

2024-12-23 13:34 UTC, aaronzi commented on aas-web-ui/src/components/Plugins/Submodels/Nameplate_v2.0.vue
I would advise against showing the language next to the text in the tables shown in the plugin. When a MultilanguageProperty has an element but no text in it, don't show any text at all (currently just the language is shown). 

I also noticed that the company logo does not show anymore and the address calculation seems to have a small issue as well. For my it just shows the country.

2024-12-24 07:09 UTC, seicke commented on aas-web-ui/src/components/Plugins/Submodels/Nameplate_v2.0.vue
Regarding MultiLanguageProperty: In [`4c78603`](https://github.com/eclipse-basyx/basyx-aas-web-ui/pull/176/commits/4c786034bb82ec1c2ca631987d8c882df8976ef7) I fixed showing a LangStringSet without text

Regarding company logo and address calculation: Can you send me your tested AAS so that I can check the issues?

2025-01-04 13:46 UTC, aaronzi requested changes
Thank you for this PR.

For now, I have two major remarks:

1. I would prefer not to include another icon dependency. I don't think that flag icons add a big benefit here and they increase the package size by a lot.
2. I noticed that now Plugins are only rendered after all the data has loaded and is available. This makes the skeleton loaders in those plugins irrelevant and increases the time before the user can see components drastically. This also includes long blocking times for the DOM since the rendering needs to wait for asynchronous actions like fetching the data from a server.

2025-01-29 08:33 UTC, closed without merging