Fix for issue #94
eclipse-basyx/basyx-aas-web-ui pull request #96
Opened 2024-11-12 07:20 UTC by seicke

# Pull Request Template

## Description of Changes

Max height for asset thumbnail is set to 30% of the document height.

## Related Issue

[Issue #94](https://github.com/eclipse-basyx/basyx-aas-web-ui/issues/94)

## BaSyx Configuration for Testing

https://github.com/eclipse-basyx/basyx-java-server-sdk/tree/main/examples/BaSyxMinimal
## AAS Files Used for Testing

2024-11-12 09:35 UTC, aaronzi requested changes
Thank you for the fix. I would advise against dynamically calculating the max-height based on the screen height. This could cause potential issues on mobile for example. My suggestion would be to use a static px value. Something around 300px would probably work very well.

2024-11-12 14:43 UTC, aaronzi requested changes
Thank you for addressing this issue. I tried review your PR on mobile devices as well and noticed that the thumbnail wasn't shown anymore:

![image](https://github.com/user-attachments/assets/baea4bc9-ed20-4f9e-85bc-44e7e34f6cbf)

Something seems to be off with the dynamic max-height calculation.

2024-11-13 16:51 UTC, seicke commented
[AASX for testing purpose.zip](https://github.com/user-attachments/files/17736193/AASX.for.testing.purpose.zip) for realisation of proposal: https://github.com/eclipse-basyx/basyx-aas-web-ui/issues/89#issuecomment-2470641847

2024-11-14 11:47 UTC, aaronzi approved these changes

2024-11-14 14:29 UTC, merged